stages:
  preprocessing:
    cmd: python src/preprocessing.py
    deps:
    - data/raw
    - src/preprocessing.py
    outs:
    - data/preprocessed
  training:
    cmd: python src/train.py
    deps:
    - data/preprocessed
    - src/dataset.py
    - src/model.py
    - src/train.py
    outs:
    - outputs/training
